# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 083708ace2a4c570b3f8956d3a31d2e14662d65b6d0ed3e02a31bc8703bb6e5612cf0180315abd0888670100c577e4d2ae5a673e4abe6b325747cbee9d46c25f

test:
  secret_key_base: cdd1d393506cb03002e4d409bf3df2be3a3ce076471d00201a3f327424f3e9c0a56ec9b0eef37c226c6ebaab8beea27c1234b83cc51c4f6621091b7621d7f2c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
